### ISSUE TITLE
license file missing

### ISSUE THREAD

**Issue by kampfgnu** [andrealufino/ALSystemUtilities#9]
its not really a problem, but FYI:
while installing via cocoapods, this message pops up:
[!] Unable to read the license file `/../Pods/ALSystemUtilities/LICENSE` for the spec `ALSystemUtilities (1.0)

**Comment by andrealufino** [comment]
Thanks for the feedback!
I’ll fix it soon!
The license is MIT

------------------------------------
Andrea Mario Lufino
iOS Dev & Expert
http://about.aliosdev.com
andrea.lufino@me.com
------------------------------------

**Comment by kampfgnu** [comment]
no problem, thanks for the library by the way!

**Comment by andrealufino** [comment]
You’re welcome :)

------------------------------------
Andrea Mario Lufino
iOS Dev & Expert
http://about.aliosdev.com
andrea.lufino@me.com
------------------------------------

**Comment by kexoth** [comment]
:+1: for the library, but this is still missing :)

**Comment by andrealufino** [comment]
Added :)
